"use client";
import HomeIcon from '@mui/icons-material/Home';
import SearchIcon from '@mui/icons-material/Search';
import ExploreIcon from '@mui/icons-material/Explore';
import SlideshowIcon from '@mui/icons-material/Slideshow';
import ChatIcon from '@mui/icons-material/Chat';
import FavoriteBorderIcon from '@mui/icons-material/FavoriteBorder';
import AddCircleOutlineIcon from '@mui/icons-material/AddCircleOutline';
import MenuIcon from '@mui/icons-material/Menu';
import LogoutIcon from '@mui/icons-material/Logout';
import "../globals.css"
import Link from 'next/link'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
          <body suppressHydrationWarning>
            <div>
                <div className='sidenav'>
                  <img className='sidenav_img ' src="https://i0.wp.com/www.dafontfree.io/wp-content/uploads/2020/12/instagram-new.png?resize=1100%2C750&ssl=1" />
                  <div className='sidenav_buttons '>
                    <button className='side_button'>
                      <HomeIcon />
                      <span>Home</span>
                    </button>
                    <button className='side_button'>
                      <SearchIcon />
                      <span>Search</span>
                    </button>
                    <button className='side_button'>
                      <ExploreIcon />
                      <span>Explore</span>
                    </button>
                    <button className='side_button'>
                      <SlideshowIcon />
                      <span>Reels</span>
                    </button>
                    <button className='side_button'>
                      <ChatIcon />
                      <span>Messages</span>
                    </button>
                    <button className='side_button'>
                      <FavoriteBorderIcon />
                      <span>Notifications</span>
                    </button>
                    <button className='side_button'>
                      <AddCircleOutlineIcon />
                      <Link href="/create">
                        <span>Create</span>
                      </Link>
                    </button>
                  </div>
                  <div className="sidenav_menu">
                    <button className='side_button'>
                      <LogoutIcon />
                      <span>Log Out</span>
                    </button>
                    <button className='side_button'>
                      <MenuIcon />
                      <span>Menu</span>
                    </button>
                  </div>
                </div>
            </div>

            
            {children}
          </body>
    </html>
  )
}
