"use client"
import HomeIcon from '@mui/icons-material/Home';
import SearchIcon from '@mui/icons-material/Search';
import ExploreIcon from '@mui/icons-material/Explore';
import SlideshowIcon from '@mui/icons-material/Slideshow';
import ChatIcon from '@mui/icons-material/Chat';
import FavoriteBorderIcon from '@mui/icons-material/FavoriteBorder';
import AddCircleOutlineIcon from '@mui/icons-material/AddCircleOutline';
import MenuIcon from '@mui/icons-material/Menu';
import PersonAddIcon from '@mui/icons-material/PersonAdd';
import "../globals.css"

import {
  Menu,
  MenuHandler,
  MenuList,
  MenuItem,
  Button,
} from "@material-tailwind/react";

import Link from "next/link"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <div>
          <nav>
            <div className='sidenav'>
              <img className='sidenav_img py-4' src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQjgOH-_XHjgCYAthu0wZgr2ugKpb4xNE94zQIjsktW&s" />
              <div className='sidenav_buttons'>
                <Link href="">
                  <button className='side_button'>
                    <HomeIcon />
                    <span>Home</span>
                  </button>
                </Link>
                <button className='side_button'>
                  <SearchIcon />
                  <span>Search</span>
                </button>
                <button className='side_button'>
                  <ExploreIcon />
                  <span>Explore</span>
                </button>
                <button className='side_button'>
                  <SlideshowIcon />
                  <span>Reels</span>
                </button>
                <button className='side_button'>
                  <ChatIcon />
                  <span>Messages</span>
                </button>
                <button className='side_button'>
                  <PersonAddIcon />
                  <span>People</span>
                </button>
                <Link href="">
                  <button className='side_button'>
                    <AddCircleOutlineIcon />
                    <span>Create</span>
                  </button>
                </Link>
              </div>
              <div className="sidenav_menu">
                <Menu>
                  <MenuHandler>
                    <button className='side_button'>
                      <MenuIcon />
                      <span>Menu</span>
                    </button>
                  </MenuHandler>
                  <MenuList>
                    <MenuItem>Saved Posts</MenuItem>
                    <MenuItem>Theme</MenuItem>
                    <MenuItem>Log Out</MenuItem>
                  </MenuList>
                </Menu>
              </div>
            </div>
          </nav>
          {children}
        </div>
      </body>
    </html>
  )
}
